import './globals.css';
import Navbar from './Navbar';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar/>
        {children}
        </body>
    </html>
  );
}
