import img1 from '@/public/productsImage/5.png';
import img2 from '@/public/productsImage/2.png';
import img3 from '@/public/productsImage/1.png';
import img4 from '@/public/productsImage/2.png';
import img5 from '@/public/productsImage/11.png';
import img6 from '@/public/productsImage/2.png';
import img7 from '@/public/productsImage/5.png';
import img8 from '@/public/productsImage/2.png';
import img9 from '@/public/productsImage/11.png';
import img10 from '@/public/productsImage/1.png';
import img11 from '@/public/productsImage/2.png';

export const products = [
  {
    id: 1,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img1,
  },
  {
    id: 2,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img2,
  },
  {
    id: 3,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img3,
  },
  {
    id: 4,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img4,
  },
  {
    id: 5,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img5,
  },
  {
    id: 6,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img6,
  },
  {
    id: 7,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img7,
  },
  {
    id: 8,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img8,
  },
  {
    id: 9,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img9,
  },
  {
    id: 10,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img10,
  },
  {
    id: 11,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img11,
  },
  {
    id: 12,
    name: 'Cublit Smart Watch',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    sku: 'FROX-13563',
    price: '$576.28',
    status: 'Active',
    qty: 556,
    rating: 5,
    sales: '188 / 2058',
    image: img1,
  },
];
